### ISSUE TITLE
グループ名が違います

### ISSUE THREAD

**Issue by wancom** [hatobus/SmartAgri#11]
SmartAgri/ESPinit/script/installscript-debian.shの１行目

sudo usermod -a -G dialot $USER &&
↓
sudo usermod -a -G dialout $USER &&
だと思います。

**Comment by hatobus** [comment]
あ、はい

**Comment by hatobus** [comment]
https://github.com/hatobus/SmartAgri/blob/e9ad7f01f532846d0e12726178452c92d22ab1f3/ESPinit/script/installscript-debian.sh#L1

直したよ
